#!/bin/bash
#
cat << EOF
-------------------------
🔌 symlinking dotfiles...
-------------------------
EOF

FILES_TO_LOCATIONS=(
    ".zshrc":"$HOME"
    ".gitconfig":"$HOME"
    "bindings/.skhdrc:$HOME"
    "bindings/karabiner.json:$HOME/.config/karabiner"
    "cmus/rc:$HOME/.config/cmus"
    "espanso/:$HOME/Library/Preferences"
    "nvim/init.vim:$HOME/.config/nvim"
    "nvim/colors/:$HOME/.config/nvim"
    "sioyek/keys_user.config:$HOME/Library/Application Support/sioyek"
    "sioyek/prefs_user.config:$HOME/Library/Application Support/sioyek"
    "spicetify/config-xpui.ini:$HOME/.config/spicetify"
    "vscode/settings.json:$HOME/Library/Application Support/Code/User"
    "vscode/keybindings.json:$HOME/Library/Application Support/Code/User"
    # vscode extensions are included in the brewfile, so we don't store
    # extensions.json
)

for DOTFILE_SET in "${FILES_TO_LOCATIONS[@]}"; do
    DOTFILE=$(echo "$DOTFILE_SET" | cut -d ":" -f 1)
    SYMLINK_LOC=$(echo "$DOTFILE_SET" | cut -d ":" -f 2)
    ln -s "$HOME/dotfiles/$DOTFILE" "$SYMLINK_LOC/$(basename $DOTFILE)"
done
