#!/bin/bash
function reviewCycle() {
    param=$1[@]
    files=("${!param}")
    for basefile in "${files[@]}";
    do
        file="$(pwd)/$basefile"

        echo "$file"
        if [ -f "$file" ]; then
            eval $VIEWER_CMD "$file"
        else
            echo "This file has been deleted."
        fi

        ACTION=$(gum choose \
                    --header "What would you like to do with $file?" \
                    "Stage this file" "Discard changes" "Ignore")
        case $ACTION in
          "Stage this file") git add "$file" ;;
          "Discard changes") gum confirm "Are you sure you want to discard all changes?" && eval $DISCARD_CMD "$file" ;;
           *) ;;
        esac
    done
}

function gumprint() {
    gum style --border normal --padding "0 1" $1
}

# exit if not run in a git repo
git status . > /dev/null 2>&1 || {
    gum log --structured --level error "Hmm, something went wrong. Is this a git repo?"
    exit 1
}
IFS=$'\n'

OVERVIEW=$(git status --porcelain .)
if [ -z "$OVERVIEW" ]; then
    gumprint "🫶  Nothing to commit!"
    exit 0
fi
gumprint "OVERVIEW"
gum style \
    --border normal \
    --padding "2 4" \
    "$OVERVIEW"

FILES=$(git diff --name-only)
if [ -z "$FILES" ]; then
    gumprint "🫶  No changed files!"
else
    gumprint "🧐 Reviewing changed files..."
    CHOSEN=($(echo "$FILES" | \
        gum choose --no-limit \
        --header "Which changed files would you like to review?"))
            #NOT_CHOSEN=$(echo ${FILES[@]} ${CHOSEN[@]} | tr ' ' '\n' | sort | uniq -u)
            VIEWER_CMD="git difftool --tool=nvimdiff -y"
            DISCARD_CMD="git restore"
            reviewCycle CHOSEN
fi

UNTRACKED=$(git ls-files --others --exclude-standard)
if [ -z "$UNTRACKED" ]; then
    gumprint "🫶  No untracked files!"
else
    gumprint "🚀 Reviewing untracked files..."
    U_CHOSEN=($(echo "$UNTRACKED" | \
                gum choose \
                    --no-limit \
                    --header "Which untracked files would you like to review?"))
    VIEWER_CMD="bat --paging=always"
    DISCARD_CMD="rm"
    reviewCycle U_CHOSEN
fi

gum style \
    --border normal \
    --padding "2 4" \
    "$(git status .)"

FINAL_ACTION=$(gum choose \
                --header "What would you like to do now?" \
                "Commit" "Run again" "Exit")
case $FINAL_ACTION in
  "Commit") git commit ;;
  "Run again") exec "$0" ;;
   *) ;;
esac

gumprint "🎉 Review complete!"
unset IFS
