#!/bin/bash
RED='\033[0;31m'

if [ -z $1 ]; then
    LINKFILE="/Users/nathanyeung/dotfiles/pinned-links.txt"
else
    LINKFILE=$1
fi
LINKS=$(cat $LINKFILE)
LINK_TITLES=$(echo "$LINKS" | sed "s/]([^)]*)//g" | sed 's/\[//g')

CHOICE=$(echo "$LINK_TITLES" | choose)
if [ -z "$CHOICE" ]; then
    echo -e "${RED}⚠️  No link selected!"
    exit 1
fi

LINK=$(grep -w "\[$CHOICE\]" "$LINKFILE" | head -1)
URI="$(echo "$LINK" | sed "s/[^(]*(//g" | sed "s/)//g" )"

if [[ "$CHOICE" == ::* ]]; then
    exec "$0" "$URI"
else
    open "$URI"
fi
