#!/bin/bash
RED='\033[0;31m'
git status . > /dev/null 2>&1 || {
    echo -e "${RED}⚠️  Hmm, something went wrong. Is this a git repo?"
    exit 1
}
REPO_ROOT=$(git rev-parse --show-toplevel 2>&1)
DELETED_FILES=$(
    git log --diff-filter=D \
            --summary $REPO_ROOT \
            | grep "delete mode"
)
CLEANED_FILENAMES="$(echo "$DELETED_FILES" | sed "s/delete mode [0-9]* //")"
SELECTED=$(echo "$CLEANED_FILENAMES" | fzf | xargs) # xargs to trim whitespace
FULL_SELECTED=$(echo "$REPO_ROOT/$SELECTED")
INVOLVED_COMMITS=$(echo "$FULL_SELECTED" | xargs git log --oneline --all --)
REVIVAL_HASH=$(echo "$INVOLVED_COMMITS" | fzf | awk -F' ' '{print $1}')
git checkout "$REVIVAL_HASH"^ -- "$FULL_SELECTED"
echo "🛠️ $FULL_SELECTED @ $REVIVAL_HASH restored!"
