matches:
  - trigger: /nsnip
    replace: "  - trigger: \n  replace: \"\""
  - trigger: /shrug
    replace: "¯\\_(ツ)_/¯"
  - trigger: /yay
    replace: "🫶🤩"
  - trigger: /cute
    replace: "😙✌️"
  - trigger: /cmdkey
    replace: "⌘"
  - trigger: /date
    replace: "{{dt}}"
    vars:
      - name: dt
        type: date
        params:
          format: "%Y-%m-%d"
  - trigger: /time
    replace: "{{dt}}"
    vars:
      - name: dt
        type: date
        params:
          format: "%H:%M"
  - trigger: /iso
    replace: "{{dt}}"
    vars:
      - name: dt
        type: date
        params:
          format: "%Y-%m-%d %H:%M:%S"
